CREATE TABLE roles (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       name VARCHAR(50) NOT NULL UNIQUE,
       description VARCHAR(255)
);
CREATE TABLE users (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       email VARCHAR(255) NOT NULL UNIQUE,
       password_hash VARCHAR(255) NOT NULL,
       first_name VARCHAR(100) NOT NULL,
       last_name VARCHAR(100) NOT NULL,
       status VARCHAR(20) NOT NULL,
       created_at TIMESTAMP WITH TIME ZONE NOT NULL,
       updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE user_roles (
        user_id BIGINT NOT NULL,
        role_id BIGINT NOT NULL,

        PRIMARY KEY (user_id, role_id),

        CONSTRAINT fk_user_roles_user
            FOREIGN KEY (user_id)
                REFERENCES users(id)
                ON DELETE CASCADE,

        CONSTRAINT fk_user_roles_role
            FOREIGN KEY (role_id)
                REFERENCES roles(id)
                ON DELETE CASCADE
);
CREATE TABLE addresses (
           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           user_id BIGINT NOT NULL,

           address_type VARCHAR(20) NOT NULL,
           recipient_name VARCHAR(150) NOT NULL,

           address_line1 VARCHAR(255) NOT NULL,
           address_line2 VARCHAR(255),

           city VARCHAR(100) NOT NULL,
           state VARCHAR(100) NOT NULL,
           postal_code VARCHAR(20) NOT NULL,
           country VARCHAR(100) NOT NULL,

           is_default BOOLEAN NOT NULL DEFAULT FALSE,

           created_at TIMESTAMP WITH TIME ZONE NOT NULL,
           updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

           CONSTRAINT fk_addresses_user
               FOREIGN KEY (user_id)
                   REFERENCES users(id)
                   ON DELETE CASCADE
);
CREATE INDEX idx_addresses_user_id
    ON addresses(user_id);

CREATE UNIQUE INDEX ux_addresses_default_user
    ON addresses(user_id)
    WHERE is_default = TRUE;