
CREATE TABLE categories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

        name VARCHAR(100) NOT NULL UNIQUE,
        description VARCHAR(500),

        status VARCHAR(20) NOT NULL,

        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE brands (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

        name VARCHAR(100) NOT NULL UNIQUE,
        description VARCHAR(500),

        status VARCHAR(20) NOT NULL,

        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE products (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

          category_id BIGINT NOT NULL,
          brand_id BIGINT NOT NULL,

          name VARCHAR(200) NOT NULL,
          description TEXT,

          status VARCHAR(20) NOT NULL,

          created_at TIMESTAMP WITH TIME ZONE NOT NULL,
          updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

          CONSTRAINT fk_products_category
              FOREIGN KEY (category_id)
                  REFERENCES categories(id),

          CONSTRAINT fk_products_brand
              FOREIGN KEY (brand_id)
                  REFERENCES brands(id)
);

CREATE INDEX idx_products_category_id
    ON products(category_id);

CREATE INDEX idx_products_brand_id
    ON products(brand_id);