
CREATE TABLE categories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

        name VARCHAR(100) NOT NULL UNIQUE,
        description VARCHAR(500),

        status VARCHAR(20) NOT NULL,

        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE brands (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

        name VARCHAR(100) NOT NULL UNIQUE,
        description VARCHAR(500),

        status VARCHAR(20) NOT NULL,

        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE products (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

          category_id BIGINT NOT NULL,
          brand_id BIGINT NOT NULL,

          name VARCHAR(200) NOT NULL,
          description TEXT,

          status VARCHAR(20) NOT NULL,

          created_at TIMESTAMP WITH TIME ZONE NOT NULL,
          updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

          CONSTRAINT fk_products_category
              FOREIGN KEY (category_id)
                  REFERENCES categories(id),

          CONSTRAINT fk_products_brand
              FOREIGN KEY (brand_id)
                  REFERENCES brands(id)
);

CREATE INDEX idx_products_category_id
    ON products(category_id);

CREATE INDEX idx_products_brand_id
    ON products(brand_id);


CREATE TABLE product_variants (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

          product_id BIGINT NOT NULL,

          sku VARCHAR(100) NOT NULL UNIQUE,
          name VARCHAR(150) NOT NULL,

          price NUMERIC(12, 2) NOT NULL,

          status VARCHAR(20) NOT NULL,

          created_at TIMESTAMP WITH TIME ZONE NOT NULL,
          updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

          CONSTRAINT fk_product_variants_product
              FOREIGN KEY (product_id)
                  REFERENCES products(id),

          CONSTRAINT chk_product_variants_price
              CHECK (price >= 0)
);

CREATE INDEX idx_product_variants_product_id
    ON product_variants(product_id);